-- ============================================================================
-- SRJE - Sistema de Retenciones Judiciales de Empleados
-- Script 03: Indices
-- Base de Datos: Oracle 19c
-- Ejecutar despues de: 01 y 02
-- ============================================================================

-- BENEFICIARIOS
-- NOTA: IDX_BENEF_RUT eliminado — UK_BENEFICIARIOS_RUT ya crea indice implicito
CREATE INDEX IDX_BENEF_NOMBRE ON BENEFICIARIOS(NOMBRE_BENEFICIARIO);
CREATE INDEX IDX_BENEF_ESTADO ON BENEFICIARIOS(ESTADO);
CREATE INDEX IDX_BENEF_COD_BANCO ON BENEFICIARIOS(COD_BANCO);

-- FUNCIONARIOS
-- NOTA: IDX_FUNC_RUT eliminado — UK_FUNCIONARIOS_RUT ya crea indice implicito

-- RETENIDO_JUDICIAL
CREATE INDEX IDX_RETEN_RUT_TITULAR ON RETENIDO_JUDICIAL(RUT_TITULAR);
CREATE INDEX IDX_RETEN_RUT_BENEF ON RETENIDO_JUDICIAL(RUT_BENEFICIARIO);
CREATE INDEX IDX_RETEN_PERIODO ON RETENIDO_JUDICIAL(PERIODO_PROCESO);
CREATE INDEX IDX_RETEN_ESTADO ON RETENIDO_JUDICIAL(ESTADO);
CREATE INDEX IDX_RETEN_COD ON RETENIDO_JUDICIAL(COD_RETENCION);

-- HISTORIAL_PAGOS_TEMGE
CREATE INDEX IDX_HIST_FECHA ON HISTORIAL_PAGOS_TEMGE(FECHA_PROCESO);
CREATE INDEX IDX_HIST_ESTADO ON HISTORIAL_PAGOS_TEMGE(ESTADO);

-- DETALLE_PAGO_TEMGE
CREATE INDEX IDX_DET_HISTORIAL ON DETALLE_PAGO_TEMGE(ID_HISTORIAL);
CREATE INDEX IDX_DET_RUT ON DETALLE_PAGO_TEMGE(RUT_BENEFICIARIO);

-- LOG_CARGAS
CREATE INDEX IDX_LOG_TIPO ON LOG_CARGAS(TIPO_CARGA);
CREATE INDEX IDX_LOG_PERIODO ON LOG_CARGAS(PERIODO_PROCESO);
CREATE INDEX IDX_LOG_ESTADO ON LOG_CARGAS(ESTADO);
CREATE INDEX IDX_LOG_HASH ON LOG_CARGAS(HASH_ARCHIVO);
CREATE INDEX IDX_LOG_FECHA ON LOG_CARGAS(FECHA_INICIO);

-- LOG_CARGA_DETALLE
CREATE INDEX IDX_LOGDET_CARGA ON LOG_CARGA_DETALLE(ID_CARGA);
CREATE INDEX IDX_LOGDET_RUT ON LOG_CARGA_DETALLE(RUT_REFERENCIA);

-- AUDITORIA_CAMBIOS
CREATE INDEX IDX_AUD_ENTIDAD ON AUDITORIA_CAMBIOS(ENTIDAD, ID_ENTIDAD);
CREATE INDEX IDX_AUD_RUT ON AUDITORIA_CAMBIOS(RUT_AFECTADO);
CREATE INDEX IDX_AUD_FECHA ON AUDITORIA_CAMBIOS(FECHA);
CREATE INDEX IDX_AUD_USUARIO ON AUDITORIA_CAMBIOS(USUARIO);

-- NOTA: Indices de API_CLIENTES y LOG_API_ACCESOS eliminados
-- (tablas removidas del esquema, sin implementacion en backend)
